return {
  -- 'okuuva/auto-save.nvim',
  -- version = '^1.0.0',
  -- cmd = 'ASToggle', -- optionnel, lazy loading à la commande
  -- opts = {
  --   enabled = true, -- start auto-save when the plugin is loaded (i.e. when your package manager loads it)
  --   condition = function(buf)
  --     local fn = vim.fn
  --     local utils = require 'auto-save.utils.data'
  --
  --     if
  --       fn.getbufvar(buf, '&modifiable') == 1
  --       -- change here is adding harpoon file type to exclusion list 
  --       and utils.not_in(fn.getbufvar(buf, '&filetype'), { 'harpoon' })
  --     then
  --       return true
  --     end
  --     return false
  --   end, -- if set to `nil` then no specific condition is applied
  -- }, -- configuration par défaut, ou personnalisez ici
  -- -- function that takes the buffer handle and determines whether to save the current buffer or not
  -- -- return true: if buffer is ok to be saved
  -- -- return false: if it's not ok to be saved
}
